### ISSUE TITLE
bits_per_word question (documentation)

### ISSUE THREAD

**Issue by ToBeReplaced** [tomstokes/python-spi#2]
`bits_per_word` defaults to 0 in the read/write/transfer functions.

The documentation says it is an optional override, with 0 equivalent to 8 bits per word. If I create an `SPI` instance with `bits_per_word=16`, will a write with no override be 8 bits per word or 16?

Thanks for the no-nonsense spidev library. I'm grateful that you took the time to open source this utility.

**Comment by tomstokes** [comment]
The documentation was incorrect, so thanks for pointing that out. A value of 0 (default) will fall back to the underlying spidev setting, which defaults to 8. I've fixed the documentation to correct that mistake.

Along those lines: Using the spidev interface with bits_per_word greater than 8 is currently a poor developer experience, because the methods only accept 8-bit words and you're forced to double up on 8-bit word entries instead of just passing an array of n-bit values.

Would you prefer if the functions accepted an array of 16-bit values? I hesitate to make that change because it breaks backwards compatibility, but technically the package is still in a sort of beta phase.

**Comment by ToBeReplaced** [comment]
@tomstokes Thanks for the clarification. My company is using a different in-house library at this point, so I don't have a preference. Unfortunately, our library cannot be open sourced at this time.

The way we handle this problem is to have a lifecycle'd `device` object that opens the device and configures it. Then we have a `prepare_transfer` function that calculates the ioctl number from a variable number of (packed) messages into a callable. To perform a transfer, one mutates the corresponding message buffers in place and calls the function returned by `prepare_transfer`. The distinction between read/write/transfer is dropped altogether and the 8 vs 16 (or 9) issue disappears.

The main difference between this approach and your library is that we pack our messages as a separate step from transfer for both extensibility and speed. Usually (always?) we pack a few messages at the start of the application and then mutate the buffers each time we want to send data.
